{{- $crossplane := .Values.operatorApplications.crossplane -}}
{{- if $crossplane.enabled -}}
{{- include "liferay-platform.requireAPIServerSources" (dict "apiServerSources" .Values.networkPolicy.apiServerSources "operatorApplication" "crossplane") -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
    labels:
        {{- include "liferay-platform.labels" $ | nindent 8 }}
    name: crossplane-function-grpc-ingress
    namespace: {{ $crossplane.namespace }}
spec:
    ingress:
        -   from:
                -   podSelector:
                        matchLabels:
                            app: crossplane
                            release: {{ $crossplane.name }}
            ports:
                -   port: grpc
                    protocol: TCP
    podSelector:
        matchExpressions:
            -   key: pkg.crossplane.io/function
                operator: Exists
    policyTypes:
        -   Ingress
{{- if .Values.observability.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
    labels:
        {{- include "liferay-platform.labels" $ | nindent 8 }}
    name: crossplane-metrics-ingress
    namespace: {{ $crossplane.namespace }}
spec:
    ingress:
        -   from:
                -   namespaceSelector:
                        matchLabels:
                            kubernetes.io/metadata.name: {{ .Values.observability.namespace }}
            ports:
                -   port: metrics
                    protocol: TCP
    podSelector: {}
    policyTypes:
        -   Ingress
{{- end }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
    labels:
        {{- include "liferay-platform.labels" $ | nindent 8 }}
    name: crossplane-provider-webhook-ingress
    namespace: {{ $crossplane.namespace }}
spec:
    ingress:
        -   from:
                {{- toYaml .Values.networkPolicy.apiServerSources | nindent 16 }}
            ports:
                -   port: 9443
                    protocol: TCP
    podSelector:
        matchExpressions:
            -   key: pkg.crossplane.io/provider
                operator: Exists
    policyTypes:
        -   Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
    labels:
        {{- include "liferay-platform.labels" $ | nindent 8 }}
    name: crossplane-webhook-ingress
    namespace: {{ $crossplane.namespace }}
spec:
    ingress:
        -   from:
                {{- toYaml .Values.networkPolicy.apiServerSources | nindent 16 }}
            ports:
                -   port: 9443
                    protocol: TCP
    podSelector:
        matchLabels:
            app: crossplane
            release: {{ $crossplane.name }}
    policyTypes:
        -   Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
    labels:
        {{- include "liferay-platform.labels" $ | nindent 8 }}
    name: default-deny-ingress
    namespace: {{ $crossplane.namespace }}
spec:
    podSelector: {}
    policyTypes:
        -   Ingress
{{- end -}}