{{- $externalSecrets := .Values.operatorApplications.externalSecrets -}}
{{- if $externalSecrets.enabled -}}
{{- include "liferay-platform.requireAPIServerSources" (dict "apiServerSources" .Values.networkPolicy.apiServerSources "operatorApplication" "externalSecrets") -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
    labels:
        {{- include "liferay-platform.labels" $ | nindent 8 }}
    name: default-deny-ingress
    namespace: {{ $externalSecrets.namespace }}
spec:
    podSelector: {}
    policyTypes:
        -   Ingress
{{- if .Values.observability.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
    labels:
        {{- include "liferay-platform.labels" $ | nindent 8 }}
    name: external-secrets-metrics-ingress
    namespace: {{ $externalSecrets.namespace }}
spec:
    ingress:
        -   from:
                -   namespaceSelector:
                        matchLabels:
                            kubernetes.io/metadata.name: {{ .Values.observability.namespace }}
            ports:
                -   port: metrics
                    protocol: TCP
    podSelector: {}
    policyTypes:
        -   Ingress
{{- end }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
    labels:
        {{- include "liferay-platform.labels" $ | nindent 8 }}
    name: external-secrets-webhook-ingress
    namespace: {{ $externalSecrets.namespace }}
spec:
    ingress:
        -   from:
                {{- toYaml .Values.networkPolicy.apiServerSources | nindent 16 }}
            ports:
                -   port: webhook
                    protocol: TCP
    podSelector:
        matchLabels:
            app.kubernetes.io/instance: {{ $externalSecrets.name }}
            app.kubernetes.io/name: external-secrets-webhook
    policyTypes:
        -   Ingress
{{- end -}}